In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import integrate

sns.set()

$$
u_t = u_xx, \\
\xi ^i = \sin \pi i x, \quad \xi ^ {i} _{xx} = -\lambda _i \xi ^i (x) \\
{l_i (x)} - \text{ какие-то функции, например $l_i (x) = \xi ^i = \sin \pi i x$}, \\
l(x) = \sum _{i=1}^{i_0} c_i l^i (x) \\
\text{Найти $l^i$: } 
(u^0(x) + l(x), \xi ^i) = 0
$$

### Этап первый: прогаем задачу в простом случае

In [3]:
def xi(i):
    def xi_i(x):
        return np.sin(np.pi * x * i)
    return xi_i

def l(i):
    def l_i(x):
        if x < 0.5:
            return np.sin(np.pi * x * i)
        else:
            return 0
    return l_i

def u0(x):
    return np.sin(np.pi * x)

def scalar_product(f1, f2):
    return integrate.quad(lambda x: f1(x) * f2(x), 0., 1.)[0]

In [4]:
N = 1

A = np.zeros((N, N))

for i in range(N):
    for j in range(N):
        A[i][j] = scalar_product(xi(i + 1), l(j + 1))

In [5]:
np.array([scalar_product(u0, xi(i)) for i in range(1, N + 1)])

array([0.5])

In [6]:
np.linalg.solve(A, np.array([scalar_product(u0, xi(i)) for i in range(1, N + 1)]))

array([2.])

### Этап второй: исследуем поправку в зависимости от объема пространства, где $l_i > 0$

In [7]:
N = 2

In [8]:
def popravka(l_volume, xi):
    def l(i):
        def l_i(x):
            if x < l_volume:
                return np.sin(np.pi * x * i)
            else:
                return 0
        return l_i
    return np.linalg.solve(np.array([[scalar_product(xi(i + 1), l(j + 1)) for i in range(N)] for j in range(N)]), 
                           np.array([scalar_product(u0, xi(i)) for i in range(1, N + 1)]))

In [9]:
grid = [1 / (2 ** i) for i in range(6)]
plt.plot(grid, [popravka(g) for g in grid])
# plt.xscale('log')
plt.yscale('log')

TypeError: popravka() missing 1 required positional argument: 'xi'

### Этап 3: меняем базис

In [98]:
def xi(i):
    def xi_i(x):
        return np.sin(np.pi * x * i)
    return xi_i

def u0(x):
    return np.sin(np.pi * x)

In [107]:
def popravka(delta, xi, N):
    def l(i):
        def l_i(x):
            if x < delta:
                return np.sin(np.pi * x * i / delta) 
            else:
                return 0
        return l_i
    return np.linalg.solve(np.array([[scalar_product(xi(i + 1), l(j + 1)) for i in range(N)] for j in range(N)]), 
                           np.array([scalar_product(u0, xi(i)) for i in range(1, N + 1)]))

In [108]:
popravka(0.5, xi, 2)

array([0., 2.])

In [ ]:
scalar_product(xi(1))